server.port=8080
spring.application.name=api-gateway

# Downstream service URLs
instagram.user-service.url=http://localhost:8081
instagram.post-service.url=http://localhost:8082
instagram.feed-service.url=http://localhost:8083
instagram.engagement-service.url=http://localhost:8084
instagram.search-service.url=http://localhost:8085
instagram.notification-service.url=http://localhost:8086
spring.banner.location=classpath:banner.txt