server.port=8082
spring.application.name=post-service

# Inter-service URLs
instagram.user-service.url=http://localhost:8081
instagram.feed-service.url=http://localhost:8083
instagram.search-service.url=http://localhost:8085
